services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: query-tool
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./internal/init_table.sql:/docker-entrypoint-initdb.d/001.sql
      - ./internal/init_demodata.sql:/docker-entrypoint-initdb.d/002.sql
    ports:
      - 5442:5432